#!/bin/bash

echo "=========================================="
echo "GET RAILWAY DATABASE CREDENTIALS"
echo "=========================================="
echo ""
echo "1. Go to: https://railway.app"
echo "2. Login to your account"
echo "3. Select project: imaginative-trust"
echo "4. Click on: PostgreSQL database"
echo "5. Click on: Connect tab"
echo "6. Copy the values shown"
echo ""
echo "You'll see something like:"
echo ""
echo "PGHOST=monorail.proxy.rlwy.net"
echo "PGPORT=12345"
echo "PGDATABASE=railway"
echo "PGUSER=postgres"
echo "PGPASSWORD=xxxxxxxxxxxxx"
echo ""
echo "=========================================="
echo "THEN UPDATE .env.local WITH THESE VALUES"
echo "=========================================="
echo ""
echo "File location: $(pwd)/.env.local"
echo ""
